/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dj2.gui;

import dj2.core.*;
import static dj2.persistence.PersistentCollection.collection;
import static dj2.gui.MainFrame.playingPane;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Pavilion
 */
public class PlaylistPane extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    ArrayList<Track> tracks;
    /**
     * Creates new customizer PlaylistPane
     */
    public PlaylistPane() {
        jList = new JList();
       DefaultListModel dlm = new DefaultListModel();
        try{
        
        for(int i=0; collection.recentlyPlayed.get(i) != null ;i++)
                dlm.add(i, collection.recentlyPlayed.get(i));
        }
        catch(NullPointerException e){}
        finally{
            initComponents();
            jList.setModel(dlm);
        }
       
        
    }
    
    @Override
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jTitle = new javax.swing.JLabel();
        jSample = new javax.swing.JLabel();
        jPlayNowButton = new javax.swing.JButton();
        jRefreshButton = new javax.swing.JButton();

        jList.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jListMouseMoved(evt);
            }
        });
        jList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jListMouseEntered(evt);
            }
        });
        jScrollPane.setViewportView(jList);

        jTitle.setText("Recently Played Playlist");

        jSample.setText(" Title           |   style   |   Type   |  duration  |      Artist/group     |      Album/Concert");
        jSample.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPlayNowButton.setText("Play now!");
        jPlayNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayNowButtonActionPerformed(evt);
            }
        });

        jRefreshButton.setText("Refresh");
        jRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPlayNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSample, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitle)
                .addGap(15, 15, 15)
                .addComponent(jSample)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPlayNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseMoved
        // TODO add your handling code here:
         
        
       
    }//GEN-LAST:event_jListMouseMoved

    private void jPlayNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayNowButtonActionPerformed
        // TODO add your handling code here:
        Track t = (Track)jList.getSelectedValue();
        playingPane.setPlaying(t);
    }//GEN-LAST:event_jPlayNowButtonActionPerformed

    private void jListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jListMouseEntered

    private void jRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshButtonActionPerformed
        DefaultListModel dlm = new DefaultListModel();
        if (collection.recentlyPlayed == null)
                return;
        for(int i=0; collection.recentlyPlayed.get(i) != null ;i++)
             dlm.add(i, collection.recentlyPlayed.get(i));
         jList.setModel(dlm);
    }//GEN-LAST:event_jRefreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList;
    private javax.swing.JButton jPlayNowButton;
    private javax.swing.JButton jRefreshButton;
    private javax.swing.JLabel jSample;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel jTitle;
    // End of variables declaration//GEN-END:variables
}
